debug: true
database_url: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
base_url: "http://localhost:8080"
migration_source: "file:///internal/database/migrations"
allow_origins:
  - "*"